module.exports = {
  defaultServerResponse: {
    status: 400,
    body: [],
    error: {},
    message: "",
  },
  validationMessage: {
    VALIDATION_FAILED: "Validation Failed",
    TOKEN_MISSING: "Token is Missing, Login First",
  },
  adminMessage: {
    CUSTOMER_CREATED: "Admin Register Successfully!",
  },
  customerMessage: {
    CUSTOMER_CREATED: "Customer Register Successfully!",
    CUSTOMER_NOT_FETCHED: "Customer not Fetched!",
    CUSTOMER_NOT_DELETED: "Customer not Deleted",
    CUSTOMER_DELETED: "Customer Deleted!",
    ADDRESS_NOT_ADDED: "Address not Added!",
    ADDRESS_NOT_DELETE: "Address not Delete!",
    ADDRESS_NOT_UPDATED: "Address not Updated!",
    ADDRESS_NOT_FOUND: "Address not Found!",
    ADDRESS_ADDED: "Address Successfully Added!",
    ADDRESS_FETCHED: "Address Fetched!",
    ADDRESS_UPDATED: "Address Successfully Updated!",
    ADDRESS_DELETED: "Address Successfully Deleted!",
    CUSTOMER_FETCHED: "Customer Profile Fetched Successfully!",
    CUSTOMER_NOT_FOUND: "Customer Not Found!",
    CUSTOMER_NOT_UPDATE: "Profile Not Found!",
    CUSTOMER_UPDATE: "Profile Updated Successfully!",
    CUSTOMER_VERIFICATION_FAILED: "Account Verification Failed!",
    CUSTOMER_VERIFIED: "Account Verified!",
    OTP_SEND: "OTP Send to Your Email!",
    TRANSACTION_ADDED: "Transaction Added Successfully!",
    TRANSACTION_NOT_ADDED: "Transaction not Added!",
  },
  authMessage: {
    EMAIL_EXISTS: "Email already Exists!",
    NEED_VERIFICATION: "Need Verification",
    NEED_LOGIN: "Need Login",
    ACCOUNT_DISABLED: "Account Disabled",
    INVALID_EMAIL: "Invalid Email!",
    INVALID_PASSWORD: "Password is Wrong!",
    LOGIN_SUCCESS: "Successfully Logedin",
  },

  categoryMessage: {
    CATEGORY_CREATED: "Category Created Successfully!",
    CATEGORY_NOT_CREATED: "Category not Created!",
    CATEGORY_UPDATED: "Category Updated Successfully !",
    CATEGORY_NOT_UPDATED: "Category not Updated!",
    CATEGORY_DELETED: "Category Deleted Successfully!",
    CATEGORY_NOT_DELETED: "Category not Deleted!",
    CATEGORY_FETCHED: "Category Fetched Successfully!",
    CATEGORY_NOT_FETCHED: "Category not Fetched!",
    CATEGORY_NOT_FOUND: "Category not Found!",
    CATEGORY_ERROR: "OOPS Error with Category!",
  },
  productMessage: {
    PRODUCT_CREATED: "Product Created Successfully!",
    PRODUCT_NOT_CREATED: "Product not Created!",
    PRODUCT_UPDATED: "Product Updated Successfully !",
    PRODUCT_NOT_UPDATED: "Product not Updated!",
    PRODUCT_DELETED: "Product Deleted Successfully!",
    PRODUCT_NOT_DELETED: "Product not Deleted!",
    PRODUCT_FETCHED: "Product Fetched Successfully!",
    PRODUCT_NOT_FETCHED: "Product not Fetched!",
    PRODUCT_NOT_FOUND: "Product not Found!",
    PRODUCT_ERROR: "OOPS Error with Product!",
  },
  dealsMessage: {
    DEALS_CREATED: "Deals Created Successfully!",
    DEALS_NOT_CREATED: "Deals not Created!",
    DEALS_UPDATED: "Deals Updated Successfully !",
    DEALS_NOT_UPDATED: "Deals not Updated!",
    DEALS_DELETED: "Deals Deleted Successfully!",
    DEALS_NOT_DELETED: "Deals not Deleted!",
    DEALS_FETCHED: "Deals Fetched Successfully!",
    DEALS_NOT_FETCHED: "Deals not Fetched!",
    DEALS_NOT_FOUND: "Deals not Found!",
    DEALS_ERROR: "OOPS Error with Deals!",
  },
  couponMessage: {
    COUPON_CREATED: "Coupon Created Successfully!",
    COUPON_NOT_CREATED: "Coupon not Created!",
    COUPON_UPDATED: "Coupon Updated Successfully !",
    COUPON_NOT_UPDATED: "Coupon not Updated!",
    COUPON_DELETED: "Coupon Deleted Successfully!",
    COUPON_NOT_DELETED: "Coupon not Deleted!",
    COUPON_FETCHED: "Coupon Fetched Successfully!",
    COUPON_NOT_FETCHED: "Coupon not Fetched!",
    COUPON_NOT_FOUND: "Coupon not Found!",
    COUPON_VERIFIED: "Coupon Applied!",
    COUPON_ERROR: "OOPS Error with Coupon!",
  },
  flavourMessage: {
    FLAVOUR_CREATED: "flavour Created Successfully!",
    FLAVOUR_NOT_CREATED: "flavour not Created!",
    FLAVOUR_UPDATED: "flavour Updated Successfully !",
    FLAVOUR_NOT_UPDATED: "flavour not Updated!",
    FLAVOUR_DELETED: "flavour Deleted Successfully!",
    FLAVOUR_NOT_DELETED: "flavour not Deleted!",
    FLAVOUR_FETCHED: "flavour Fetched Successfully!",
    FLAVOUR_NOT_FETCHED: "flavour not Fetched!",
    FLAVOUR_NOT_FOUND: "flavour not Found!",
    FLAVOUR_ERROR: "OOPS Error with flavour!",
  },
  pincodeMessage: {
    PINCODE_CREATED: "Pincode Created Successfully!",
    PINCODE_NOT_CREATED: "Pincode not Created!",
    PINCODE_UPDATED: "Pincode Updated Successfully !",
    PINCODE_NOT_UPDATED: "Pincode not Updated!",
    PINCODE_DELETED: "Pincode Deleted Successfully!",
    PINCODE_NOT_DELETED: "Pincode not Deleted!",
    PINCODE_FETCHED: "Pincode Fetched Successfully!",
    PINCODE_NOT_FETCHED: "Pincode not Fetched!",
    PINCODE_NOT_FOUND: "Pincode not Found!",
    PINCODE_ERROR: "OOPS Error with Pincode!",
  },
  reviewMessage: {
    REVIEW_CREATED: "Review Created Successfully!",
    REVIEW_NOT_CREATED: "Review not Created!",
    REVIEW_UPDATED: "Review Updated Successfully !",
    REVIEW_NOT_UPDATED: "Review not Updated!",
    REVIEW_DELETED: "Review Deleted Successfully!",
    REVIEW_NOT_DELETED: "Review not Deleted!",
    REVIEW_FETCHED: "Review Fetched Successfully!",
    REVIEW_NOT_FETCHED: "Review not Fetched!",
    REVIEW_NOT_FOUND: "Review not Found!",
    REVIEW_ERROR: "OOPS Error with Review!",
  },
  shapeMessage: {
    SHAPE_CREATED: "Shape Created Successfully!",
    SHAPE_NOT_CREATED: "Shape not Created!",
    SHAPE_UPDATED: "Shape Updated Successfully !",
    SHAPE_NOT_UPDATED: "Shape not Updated!",
    SHAPE_DELETED: "Shape Deleted Successfully!",
    SHAPE_NOT_DELETED: "Shape not Deleted!",
    SHAPE_FETCHED: "Shape Fetched Successfully!",
    SHAPE_NOT_FETCHED: "Shape not Fetched!",
    SHAPE_NOT_FOUND: "Shape not Found!",
    SHAPE_ERROR: "OOPS Error with Shape!",
  },
  orderMessage: {
    ORDER_CREATED: "Order Created Successfully!",
    ORDER_NOT_CREATED: "Order not Created!",
    ORDER_UPDATED: "Order Updated Successfully !",
    ORDER_NOT_UPDATED: "Order not Updated!",
    ORDER_DELETED: "Order Deleted Successfully!",
    ORDER_NOT_DELETED: "Order not Deleted!",
    ORDER_FETCHED: "Order Fetched Successfully!",
    ORDER_NOT_FETCHED: "Order not Fetched!",
    ORDER_NOT_FOUND: "Order not Found!",
    ORDER_ERROR: "OOPS Error with Order!",
  },
  colorMessage: {
    COLOR_CREATED: "Color Created Successfully!",
    COLOR_NOT_CREATED: "Color not Created!",
    COLOR_UPDATED: "Color Updated Successfully !",
    COLOR_NOT_UPDATED: "Color not Updated!",
    COLOR_DELETED: "Color Deleted Successfully!",
    COLOR_NOT_DELETED: "Color not Deleted!",
    COLOR_FETCHED: "Color Fetched Successfully!",
    COLOR_NOT_FETCHED: "Color not Fetched!",
    COLOR_NOT_FOUND: "Color not Found!",
    COLOR_ERROR: "OOPS Error with Color!",
  },
  settingMessage: {
    SETTING_UPDATED: "Setting Updated Successfully !",
    SETTING_NOT_UPDATED: "Setting not Updated!",
    SETTING_FETCHED: "Setting Fetched Successfully!",
    SETTING_NOT_FETCHED: "Setting not Fetched!",
    SETTING_NOT_FOUND: "Setting not Found!",
    SETTING_ERROR: "OOPS Error with Setting!",
  },
  shippingMethodMessage: {
    SHIPPING_METHOD_CREATED: "Shipping Method Created Successfully!",
    SHIPPING_METHOD_NOT_CREATED: "Shipping Method not Created!",
    SHIPPING_METHOD_UPDATED: "Shipping Method Updated Successfully !",
    SHIPPING_METHOD_NOT_UPDATED: "Shipping Method not Updated!",
    SHIPPING_METHOD_DELETED: "Shipping Method Deleted Successfully!",
    SHIPPING_METHOD_NOT_DELETED: "Shipping Method not Deleted!",
    SHIPPING_METHOD_FETCHED: "Shipping Method Fetched Successfully!",
    SHIPPING_METHOD_NOT_FETCHED: "Shipping Method not Fetched!",
    SHIPPING_METHOD_NOT_FOUND: "Shipping Method not Found!",
    SHIPPING_METHOD_ERROR: "OOPS Error with Shipping Method!",
  },
  databaseMessage: {
    INVALID_OBJECTID: "Object ID is Invalid",
  },
};
